### PR TITLE
Remove unused vmap toy

### PR DESCRIPTION
**Pull request by gdbelvin**
`vmap/toy` and `vmap/rpctoy` seem unused and are acquiring bit rot.
If they have any value, they should be moved to the integration tests.

### CODE REVIEW

**Comment by Martin2112** [comment]
Another option is to move them to the examples repo, if they're still useful.

**Comment by gdbelvin** [comment]
It wasn't super clear to me if the vmap stuff was still useful.  @AlCutter ?

**Comment by Martin2112** [comment]
It was a very early demo thing.

**Comment by AlCutter** [comment]
Probably less useful these days, would be great to have a command-line tool for getting/setting/verifying leaves etc. though.

**Pull request merged**
