### PR TITLE
Always require the root parameter when creating new LogClients

### PR DESCRIPTION
**Pull request by maljub01**
Currently, users have no way of setting a starting root for the
LogClient. This means that whenever LogClient is used, the current
latest root returned by Trillian is implicitly trusted.

This change allows users to instead start verification from a known
good state. This is useful for recovering from restarts/downtime without
losing verifiability.

Clients that want the old behavior should call `New` with an empty initial
trusted log root.
    
```
New(..., types.LogRootV1{})
NewFromTree(..., types.LogRootV1{})
```

### CODE REVIEW

**Comment by gdbelvin** [comment]
`WithRoot` is actually best practice. Would you mind adding it as a required parameter to the existing `New` functions? 

Clients that want the old behavior should call  `New` with an empty initial trusted log root. 
```
New(..., types.LogRootV1{})
```

I realize this will expand the CL, but it should make it much clearer what root is initially being trusted from all the calling locations.

**Comment by maljub01** [comment]
Done. I also had to add the root parameter to `NewFromTree` which uses `New`.

**Comment by maljub01** [comment]
@gdbelvin CI seems to be failing because of gometalinter timing out, but I'm unable to retrigger the tests without pushing more commits, do you mind retriggering them?

**Comment by gdbelvin** [comment]
I've been noticing the deadline issue as well. 
* Retry that particular test in travis. I think this issue occurs when travis is under slightly increased load.
* Try increasing the deadline in `./scripts/presubmit.sh`.
* Have a chat with @Martin2112 about the deadline.

**Comment by maljub01** [comment]
Created a PR that increases the deadline: https://github.com/google/trillian/pull/1226

**Pull request merged**
