### PR TITLE
adding VDS paper as markdown

### PR DESCRIPTION
**Pull request by smeiklej**
### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Review by AlCutter — APPROVED** [review]

**Comment by getagit** [comment]
Do you want to delete the PDF version in the papers/ subdir (or maybe move the two versions closer, or something)?

**Comment by pphaneuf** [comment]
Since git is itself a "blockchain", the PDF will not disappear with anything less than a hard fork, even if you "delete" it. 😃 

What you'll get is potentially less confusion, though...

**Comment by smeiklej** [comment]
Sure, but the link to it will go away/change and there are numerous places on the internet that use the current one (and will not change it), so I have a strong preference for keeping it where it is and just making sure we update all our own pointers.

**Comment by getagit** [comment]
Agree that the old version is linked all over the place, so break without forwarding is sub-optimal.  But for people coming to the Trillian repo now, they see two versions of "VerifiableDataStructures", in different formats, in different directories, and (soon) with different content and no obvious indicator of what the difference is or which one to use, so it looks more a bug.  

Maybe the simplest is to rename the new version to "-2021"  (or "latest" or something to indicate that its the "living" version and not just the old paper in a new format)?

**Comment by smeiklej** [comment]
Okay, makes sense to rename the Markdown one - can do that once I start committing the changes we plan to make.

**Pull request merged**
