### PR TITLE
[HOTFIX] docker-compose up does not work

### PR DESCRIPTION
**Pull request by baitcode**
docker-compose up does not work due to mysql error "Access denied for root..." 

* removed quotes from password in resetdb script

Issues: HOTFIX

### CODE REVIEW

**Comment by baitcode** [comment]
I signed it!

**Comment by daviddrysdale** [comment]
I can't currently see a signed CLA -- could you double-check please?

**Comment by baitcode** [comment]
Made another attempt to sign, got an error that I've already signed doc.

**Comment by daviddrysdale** [comment]
We're not seeing a CLA for the email address in the commit itself -- is there any chance you signed the CLA against a different email?

**Comment by baitcode** [comment]
You were right. I've changed email in commit to be the one I used to sign CLA.

**Comment by daviddrysdale** [comment]
I can't see a CLA for that email either I'm afraid.

**Comment by daviddrysdale** [comment]
Closing this out for now -- please open a new PR if you sort out the CLA issue (and apologies for the awkwardness).

**Pull request closed without merging**
