### PR TITLE
etcd: Fix first WithMastership call blocking if no Await

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
This change fixes the following bug in `etcd` implementation of `election2`:
1. `Await` is not called.
2. `WithMastership` is called. It is supposed to return a closed context because the instance is not the master.
3. Instead, it blocks forever (assuming there are no other instances calling `Await`) because `Observe` hopes to get some updates which it never gets because nobody was ever the master.

Tests for this case and others will be added in separate PRs like #1386.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by Martin2112** [comment]
Not sure where we infer from the etcd docs that Observe will not do anything if nobody is master when this starts?

Going to add David to this as well as he's more familiar with etcd.

**Comment by pavelkalinnikov** [comment]
This is an actual bug that I caught with tests in #1386, and this change does fix it. Sorry for not including the tests, I will add them separately as they are quite bulky. The problem is that `Observe` only reports PUT `etcd` values. It does not report DELETE, and does not report absense of values.

**Comment by Martin2112** [comment]
Interesting. I read the etcd API docs and it wasn't obvious that this is what happens. Observe() doesn't list any preconditions and glancing at their code it looks like it bails on errors.

**Comment by pavelkalinnikov** [comment]
[This](https://github.com/etcd-io/etcd/blob/abb57363ba6fce3fea1d427841904f434c863d49/clientv3/concurrency/election.go#L197) and [this](https://github.com/etcd-io/etcd/blob/abb57363ba6fce3fea1d427841904f434c863d49/clientv3/concurrency/election.go#L231) line clarifies not returning DELETE events.
Also, the `Observe` function comment says "observes ordered leader proposals" which is basically values PUT by the leader. No leader -> no PUT values -> no stuff pushed to the channel.

**Comment by Martin2112** [comment]
OK where do these problems manifest? It looks like migrillian always calls Await(). The election interfaces and tracker utils make it harder to see where the logsigner calls it.

**Comment by pavelkalinnikov** [comment]
Correct, the problem does not show itself in reality as `Await` is always called first (in Migrillian and Key Transparency). `logsigner` does not yet use `election2`, but I am in the process of converging the 2 election interfaces that we have.

**Pull request merged**
