### PR TITLE
Don't deadlock in sequencer

### PR DESCRIPTION
**Pull request by daviddrysdale**

### CODE REVIEW

**Comment by AlCutter** [comment]
*cough*

**Comment by codingllama** [comment]
Hey folks, could we make sure we have test coverage for this scenario? It's a bit worrying that this got past Travis.

**Comment by daviddrysdale** [comment]
Pull #383 tweaks the integration tests so that they would hit this.

**Comment by codingllama** [comment]
Nice, thanks.

**Pull request merged**
