### PR TITLE
skylog: Create gcp storage folder

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
We use multiple GCP services, so it makes sense to put them in one directory.

### CODE REVIEW

**Comment by gdbelvin** [comment]
Blocked on #1400

**Comment by gdbelvin** [comment]
Rebase?

**Comment by pavelkalinnikov** [comment]
Works after the rebase. PTAL.

**Comment by gdbelvin** [comment]
Now that #1400 has been merged, we can take advantage of Trillian's go.mod declarations of dependencies. 


Please update trillian to `@HEAD` and run  `go mod tidy` to clean up any unnecessary `// indirect`s

**Pull request merged**
