### PR TITLE
Logic bug

### PR DESCRIPTION
**Pull request by gdbelvin**
Fix logic bug caused by variable shadowing.

### CODE REVIEW

**Comment by Martin2112** [comment]
Can you make PR titles more descriptive please?

**Comment by Martin2112** [comment]
It looks like the linter version bump might not be included intentionally?

**Comment by gdbelvin** [comment]
This logic bug is caught by the latest version of the linter, which is why
it's included in this PR

**Comment by Martin2112** [comment]
Which is why documenting the intention of the PR is helpful for reviewers.

**Pull request merged**
