### PR TITLE
Run CI tests against multiple versions of golang

### PR DESCRIPTION
**Pull request by pgporada**
### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
@pgporada We no longer run CI on Travis: #2298.

**Comment by pavelkalinnikov** [comment]
Are you using Go 1.14? Maybe we could just bump the version in CI. Our README anyway says "To build and test Trillian you need: Go 1.14 or later", so these should be consistent.

**Comment by pgporada** [comment]
We're currently using Go 1.14.x to build our copies of trillian and ctgo. I had wanted to rebuild our containers on Go 1.15.x and thought that having CI run tests parallelly would be good for all.

I now see that cloudbuild is going to use golang 1.15.7 per https://github.com/google/trillian/blob/master/cloudbuild.yaml#L50-L53 and https://github.com/google/trillian/blob/master/integration/cloudbuild/testbase/Dockerfile#L23.

Sorry for the time waste.

**Comment by pavelkalinnikov** [comment]
No problem at all. Yes, I think you are pretty safe to try Go 1.15. We should probably indicate it consistently across README/Dockerfiles/etc. The CI configuration is a bit messy now, because we had to do the migration quickly.

**Pull request closed without merging**
