### PR TITLE
Remove `hash_algorithm` from `Tree`.

### PR DESCRIPTION
**Pull request by pphaneuf**
Part of #2450.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by Martin2112** [comment]
Wait, this means it can only be used for CT? I didn't think that was part of the scope of this.

**Comment by pphaneuf** [comment]
It can be used for many things, but it can only use the RFC6962 hashing algorithm (which everything I could lay my eyes on uses).

**Comment by pphaneuf** [comment]
For what it's worth, this is already true: all the non-RFC6962 hashing algorithm have been removed, and any other value will return an error anyway.

**Comment by Martin2112** [comment]
@AlCutter can you comment on what the scope of the changes is meant to be?

**Comment by AlCutter** [comment]
This `hash_algorithm` is just describing the hash scheme for (now removed) signatures - logically it's part of #2466 which removed the corresponding encryption scheme for the sigs.

There's the tree `hash_strategy` which defines the Merkle node hash function, but that's separate (and now that the map is gone there is currently only the the one `RFC6962_SHA256` strategy)

**Review by AlCutter — APPROVED** [review]

**Comment by Martin2112** [comment]
OK I misunderstood then. It looked from the comments above like it was affecting tree hashing.

**Comment by pphaneuf** [comment]
Ah, yes, I was confusing the two as well, in that chain of PRs! 😄 

This here is the hashing *algorithm* "used" in the signature, and the hash *strategy* was removed in other PRs.

**Comment by Martin2112** [comment]
So we have removed the means to implement non-CT hashing? I don't think that was necessary.

**Pull request merged**
