### PR TITLE
Move golangci-lint from Cloud Build to GitHub Action

### PR DESCRIPTION
**Pull request by roger2hk**
The Cloud Build duration will be slightly shorten by moving the golangci-lint to GitHub Action workflow.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by roger2hk** [comment]
I have no clue why the trillian-pr-tests keeps failing.

**Comment by AlCutter** [comment]
Seems to be failing to look up the ip address of the DB host, although I'm not sure why this should have just started happening...

```
W1107 00:24:37.895519    2548 tree_storage.go:81] Failed to set strict mode on mysql db: dial tcp: lookup 1c8e0e9187d0_db_1 on 127.0.0.11:53: no such host
F1107 00:24:37.895561    2548 main.go:118] Failed to get storage provider: dial tcp: lookup 1c8e0e9187d0_db_1 on 127.0.0.11:53: no such host
exit status 1
```

**Comment by mhutchinson** [comment]
Any insights into what the problem with the DB connection is? Seems suspicious that it's happened so soon after the upgrade to MySQL 8, but weird that it's happening on this PR now. Looks like other PRs have gone in fine since. I've made the target re-run but I assume someone has already tried that?

**Comment by mhutchinson** [comment]
Looks like it was just a flake.

**Review by mhutchinson — APPROVED** [review]

**Comment by roger2hk** [comment]
> Looks like it was just a flake.

Thanks Martin. I guess I had some bad luck on that day.

**Pull request merged**
