### PR TITLE
Add MariaDB Tests to Travis

### PR DESCRIPTION
**Pull request by gdbelvin**
### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by mhutchinson** [comment]
Currently this is hitting problems setting up the DB, which isn't surprising. Is there a way to create a VM of the sort Travis sets up that we can interact with manually to see what the environment looks like? Otherwise installing & setting passwords/databases for this is going to be tedious. Current issue:

```
Resetting DB...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Error: Failed to drop database 'test'.
The command "./scripts/resetdb.sh --force" failed and exited with 1 during .
```

**Comment by gdbelvin** [comment]
Have a look at this:
https://andy-carter.com/blog/setting-up-travis-locally-with-docker-to-test-continuous-integration

**Comment by mhutchinson** [comment]
> Have a look at this: https://andy-carter.com/blog/setting-up-travis-locally-with-docker-to-test-continuous-integration

To save anyone else the pain & wasted time of this rabbit hole - it's a hard no. Travis moved from docker images to VMs last year. The docker images are now stale and don't represent anything like the xenial setup.

**Comment by mhutchinson** [comment]
I got this running with 10.3 in #1876 . Closing this PR.

**Pull request closed without merging**
