### PR TITLE
Migrate to dep

### PR DESCRIPTION
**Pull request by gdbelvin**
# Experimental 

Using `dep` will greatly simplify the complicated dance of keeping dependencies up-to-date.

This PR depends on #1220 being merged first, since `dep` will automatically remove anything that is not referenced by go code, including various binaries that are currently checked out.

### CODE REVIEW

**Comment by Martin2112** [comment]
For one thing it doesn't build. Also needs discussion and further thought before we do this.

**Comment by daviddrysdale** [comment]
Yeah, there's a couple of awkward points with `dep` (that I'm aware of):
 - It's a bit tricky to ensure that required command line tools get pulled into `vendor/`.
 - Our dual-repo structure with ct-go makes (in particular) some integration tests awkward.

For the former, I've got something that works but is a bit obscure.  For the latter, we need to figure out how to `dep ensure` properly between the two repos (and how to preserve the Travis integration test in the Trillian repo that ensures that changes to trillian haven't broken the CTFE personality).

As Martin says, we should discuss in person.

**Comment by Martin2112** [comment]
Can I make an unpopular suggestion? What if we move the CT code back here from the other repo ... I'll get my coat ...

**Comment by gdbelvin** [comment]
It appears that `dep` is already deprecated. 

> The Go toolchain, as of 1.11, has (experimentally) adopted an approach that sharply diverges from dep

https://github.com/golang/dep

**Pull request closed without merging**
