### PR TITLE
Add explicitly retriable error type to backoff

### PR DESCRIPTION
**Pull request by pav-kv**
Details in PR 1333 [here](https://github.com/google/trillian/pull/1333#discussion_r231950262).

### CODE REVIEW

**Comment by gdbelvin** [comment]
Is there an intended use case here that isn't covered by `status.Code`? 
See the last paragraph of [grpc statuscodes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md)

**Comment by daviddrysdale** [comment]
Having an explicitly `RetriableError` allows non-gRPC users of `client/backoff` to do retries without acquiring an otherwise-unnecessary (direct) dependency on gRPC stuff -- e.g. the `scanner.Fetcher` code in the ct-go repo that was broken by #1333, which has nothing to do with gRPC.

**Comment by pavelkalinnikov** [comment]
Hm, interesting docs, thanks.
My use-case is [here](https://github.com/google/certificate-transparency-go/pull/393/files#r232004769). My main concern is that Backoff package forces me to use gRPC codes in the first place, instead of being a general purpose algorithm. In this PR I try to address this.

**Comment by pavelkalinnikov** [comment]
Hm, maybe a slightly less efficient, but a more canonical approach would be to wrap retriable gRPC errors into `RetrieableError`, so that `Backoff` algorithm is agnostic of gRPC completely.

**Pull request merged**
