### PR TITLE
Change default values for signer --sequencer_interval and --batch_size

### PR DESCRIPTION
**Pull request by RJPercival**
- Reduce sequencer interval from 10 seconds to 100 milliseconds.
- Increase batch size from 50 to 1000.

These two changes will vastly increase the signer's throughput and decrease its latency out-of-the-box. The previous defaults would cause the integration test to fail because the signer sequenced too slowly ([integration/functions.sh](https://github.com/google/trillian/blob/edb422bee99543835719b7a8944f2109b83a34eb/integration/functions.sh#L182-L183) overrides the default values to avoid this).

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
In the PR description do you mean the latency will **decrease**?

**Comment by pavelkalinnikov** [comment]
Did you make sure there won't be too much spam in logs due to frequent signing runs? I found it quite annoying before, not sure what the current state is.

**Comment by RJPercival** [comment]
Oops, fixed the latency typo. It sounds like maybe some logging should be made verbose?

**Comment by pavelkalinnikov** [comment]
Yeah. I think the line I'm talking about is the `"Group run completed in %.2 second: ...."`. Maybe we could leave it as is (Info), but print only if there was at least 1 entry processed/failed/etc.

**Comment by pavelkalinnikov** [comment]
Alternatively, we could move it to Verbose(1), yeah.

**Comment by RJPercival** [comment]
@pavelkalinnikov: done

**Comment by daviddrysdale** [comment]
Travis logs are currently too long to be displayed, sometimes even in raw log mode -- possibly due to this PR?

**Comment by RJPercival** [comment]
It appears so - my attempt to reduce log spam wasn't sufficient, since it appears our integration tests have a great many failing signing runs.

**Comment by RJPercival** [comment]
For now, I'll revert the commit that made the integration tests use the default flag values (see PR https://github.com/google/trillian/pull/1277). Some of the log messages look a little concerning though, e.g. 
```
E0906 17:15:24.753006   21959 log_operation_manager.go:399] ExecutePass(7461448437129865060) failed: failed to integrate batch for 7461448437129865060: Expected 1 row(s) to be affected but saw: 0
```

**Pull request merged**
