### PR TITLE
Remove liveness probe for Galera instances

### PR DESCRIPTION
**Pull request by RJPercival**
If an SST was underway to replicate the database state, the recipient Galera instance would appear to be dead, according to this probe, until the SST completed. This would result in Kubernetes killing the recipient.

TODO: Devise a better liveness probe, perhaps checking whether the file "/data/mysql/sst_in_progress" exists.

### CODE REVIEW

**Comment by RJPercival** [comment]
From reading the documentation, it looks like you need to be able to connect to the server to get the wsrep status. In this scenario, the server isn't accepting connections (that's why the liveness probe was failing).

**Comment by Martin2112** [comment]
I thought the donor was up but in a desynced state. Aggregating the state
from the available nodes would maybe work. Suspiciously their monitoring
cluster status doc doesn't really cover SST monitoring.

http://galeracluster.com/documentation-webpages/monitoringthecluster.html

**Comment by RJPercival** [comment]
The donor will be up but the liveness probe I've been referring to runs on the joiner, which is down.

**Comment by Martin2112** [comment]
OK. If we were doing real monitoring we'd want to be collecting data from
all nodes to detect partitions etc. This should be OK for now as it won't
recover in the time this probe previously allowed.

**Comment by RJPercival** [comment]
Something like [mysqld_exporter for Prometheus](https://github.com/prometheus/mysqld_exporter) might be a good way to monitor the cluster in the future. That allows Prometheus to collect the wsrep_* vars, amongst others, and then presumably alerts could be set up for when a partition forms.

**Comment by Martin2112** [comment]
Yes, that sounds like a good plan.

**Comment by gdbelvin** [comment]
Slightly unrelated issue, but I tried to use the containers in the file and didn't have permissions. 
Should they be public, or is there a special group that consumers of these images need to be part of?

**Comment by RJPercival** [comment]
By default, the container image is uploaded to trillian-test's GKE container registry on GCP - you'll need to be made a member of trillian-test to access it. However, you could just upload the image elsewhere (the push.sh script has a "-t" flag) and tweak the galera.yaml file to use your image. You'd need to do this to run it on GCE under any other project anyway.

**Comment by RJPercival** [comment]
@Martin2112, ok to merge?

**Pull request merged**
