### PR TITLE
Roll back #2536, to fix generated code.

### PR DESCRIPTION
**Pull request by pphaneuf**
### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by mhutchinson** [comment]
Any context on the breakage? I'm checking this locally now, but it's surprising the presubmit tests passed on the original PR if this doesn't work.

**Comment by mhutchinson** [comment]
Ah, I'm seeing it now:

```
experimental/batchmap/batchmap.shims.go:28:2: no required module provides package github.com/apache/beam/sdks/go/pkg/beam/core/graphx/schema; to add it:
	go get github.com/apache/beam/sdks/go/pkg/beam/core/graphx/schema
```

**Review by mhutchinson — APPROVED** [review]

**Review by pavelkalinnikov — APPROVED** [review]
If you run `go get` from the error message, does it not fix the problem?

**Comment by mhutchinson** [comment]
It looks like `runtime` is missing from that generated package import path:

https://github.com/apache/beam/tree/master/sdks/go/pkg/beam/core/runtime/graphx

I've done this locally with the latest tip of tree and the generated code resolves correctly. go-beam isn't releasing with semver, though git tags are cut for java-beam and python-beam which is why there are "releases". I think we should merge this PR to roll back, and then either wait for the next minor version, or perform ad-hoc updates. I'd prefer the dependabot updates, as it's at least regular (even if the versions it proposes are basically arbitrary for the go code).

**Pull request merged**
