### PR TITLE
Various Map clarifications/tweaks

### PR DESCRIPTION
**Pull request by daviddrysdale**

### CODE REVIEW

**Comment by daviddrysdale** [comment]
A random selection of changes I've made to the code while getting to grips with the Map storage layer, to help me understand better what's going on.

Best reviewed commit-by-commit, and some of the commits might not be worth including.

**Comment by AlCutter** [comment]
LGTM but could you drop the last commit (the one which removes the subtree interface) for now?

**Comment by daviddrysdale** [comment]
Yeah, I thought you'd say that (which is why it's the last commit).

**Comment by daviddrysdale** [comment]
Close/re-open to force new Travis build with elided commit.

**Pull request merged**
