### PR TITLE
Map: Include root in GetLeaves

### LINKED ISSUE #630: Map: Sign SignedMapHead
The trillian map server does not currently sign it's tree heads.

### PR DESCRIPTION
**Pull request by gdbelvin**
Sending the SignedMapHead is nessesary for clients to verify map
inclusion proofs.

Closes #630

cc @AMarcedone

### CODE REVIEW

**Comment by Martin2112** [comment]
It doesn't look unreasonable but I was going to talk to Gary when he gets here. I don't think this adds extra work to serving requests as it has to get the root anyway.

**Comment by gdbelvin** [comment]
@codingllama Thanks for the review.  @Martin2112 I'm looking forward to coming into the office tomorrow!

**Comment by Martin2112** [comment]
Great! We've even got you a desk.

**Comment by gdbelvin** [comment]
Closed by #665

**Pull request merged**
