### PR TITLE
Rename the RPC server so it's not the same as the binary

### PR DESCRIPTION
**Pull request by Martin2112**
Should be clearer hopefully.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
Er, this feels a bit like it's heading in the wrong direction -- Go names tend to be shorter and lacking in underscores...

**Comment by Martin2112** [comment]
How about this then? Quite a few of our filenames have underscores in them. I've left the struct name as it's an RPC server for the TrillianLog API as defined in the proto, which I believe makes sense.

**Comment by Martin2112** [comment]
IMNSHO we shouldn't renaming things sooner rather than later if they involve protos or APIs. Otherwise, it's storing up work for clients and ourselves.

**Comment by daviddrysdale** [comment]
I'd only lean towards removing "Trillian.." for internal names; having it in the external-facing gRPC API is fair enough.

**Comment by Martin2112** [comment]
OK, I think we agree then.

**Pull request merged**
