### PR TITLE
log: Clean-up operation loop

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
This change simplifies log operation loop in preparation for a structural refactoring.
Review commit-by-commit.

#1640

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
PTAL. Commit-by-commit review is recommended.

**Comment by pavelkalinnikov** [comment]
Also, I recommend to "Hide whitespace changes".

**Review by AlCutter — APPROVED** [review]
Nice commi-wise PR, thanks!

**Review by Martin2112 — APPROVED** [review]
This seems to be functionally equivalent, or at least I didn't see any issues.

**Comment by pavelkalinnikov** [comment]
Travis is stuck, doesn't start any builds.

**Comment by pavelkalinnikov** [comment]
Added a mini-commit to trigger Travis again.

**Comment by pavelkalinnikov** [comment]
@Martin2112 @AlCutter I added another cosmetic commit, which eliminates the goto-like "break label" construction, by factoring out another method. You may want to review this last commit just in case.

**Review by AlCutter — APPROVED** [review]

**Comment by Martin2112** [comment]
LGTM

**Comment by pavelkalinnikov** [comment]
Nice. New integration tests in Could Build pass. I will merge this after playing with CB a little more and ensuring it has all the necessary coverage.

**Pull request merged**
