### PR TITLE
Bump CockroachDB to 22.2.17

### LINKED ISSUE #3300: CRDB Check Broken due to CockroachDB v22.1 EOL
```
2024/01/17 21:59:52 cockroach logs directory: /tmp/cockroach-testserver1754551371
2024/01/17 21:59:52 GET https://binaries.cockroachdb.com/cockroach-v23.1.14.linux-amd64.tgz
2024/01/17 21:59:52 cockroach-go testserver: Failed to fetch latest binary: error downloading https://binaries.cockroachdb.com/cockroach-v23.1.14.linux-amd64.tgz: 404 (404 Not Found) attempting to use cockroach binary from your PATH
E0117 21:59:52.931905    3719 common_test.go:29] Failed to start test server: cockroach-go testserver command cockroach version failed: exec: "cockroach": executable file not found in $PATH
FAIL	github.com/google/trillian/quota/crdbqm	0.175s
FAIL
Error: Process completed with exit code 1.
```

https://github.com/google/trillian/blob/63a7f6c9e0844d14dd3b2c4eb2265e6e4bd39f98/integration/cloudbuild/testbase/Dockerfile#L26-L27

### PR DESCRIPTION
**Pull request by roger2hk**
Fixes #3300.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by JAORMX** [comment]
```
 === CONT  TestNodeRoundTrip/store-none-read-all
E0118 01:18:30.830402    3636 subtree_cache.go:122] PopulateLogTile(): log repop got: 254 internal nodes, want: 0
```
:thinking:

**Comment by roger2hk** [comment]
> ```
> === RUN   TestLogSuite/DequeueLeavesNoneQueued
> W0118 01:18:25.752295    3636 tree_storage.go:375] TX commit error: pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/474/2/1): "sql txn" meta={id=392f48e9 key=/Table/421/1/6041628873873342746/"\x00\xe1\t\xcf\\#\xd6'U\x1e\xaf\xa6\xed\x82y\xb6.JIGn\x83Cxy\xf6\x85\xa0\xe01\x91P"/0 pri=0.01106136 epo=0 ts=1705540702.707518406,2 min=1705540701.649429217,0 seq=3000} lock=true stat=PENDING rts=1705540701.649429217,0 wto=false gul=1705540702.149429217,0, stack:
> goroutine 50 [running]:
> runtime/debug.Stack()
> 	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/debug/stack.go:24 +0x5e
> github.com/google/trillian/storage/crdb.(*treeTX).Commit(0xc000201080, {0xd36db0, 0x123c280})
> 	/home/runner/work/trillian/trillian/storage/crdb/tree_storage.go:375 +0x22d
> github.com/google/trillian/storage/crdb.(*crdbLogStorage).QueueLeaves(0xd38328?, {0xd36db0, 0x123c280}, 0x0?, {0xc00099c000, 0x3e8, 0x500}, {0x0, 0xecfb6864b, 0x0})
> 	/home/runner/work/trillian/trillian/storage/crdb/log_storage.go:301 +0x225
> github.com/google/trillian/storage/crdb.TestQueueLeavesDuplicateBigBatch(0xc000b56340)
> 	/home/runner/work/trillian/trillian/storage/crdb/log_storage_test.go:246 +0x250
> testing.tRunner(0xc000b56340, 0xc74738)
> 	/opt/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1595 +0xff
> created by testing.(*T).Run in goroutine 1
> 	/opt/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1648 +0x3ad
> === NAME  TestQueueLeavesDuplicateBigBatch
>     log_storage_test.go:247: Failed to queue leaves: pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/474/2/1): "sql txn" meta={id=392f48e9 key=/Table/421/1/6041628873873342746/"\x00\xe1\t\xcf\\#\xd6'U\x1e\xaf\xa6\xed\x82y\xb6.JIGn\x83Cxy\xf6\x85\xa0\xe01\x91P"/0 pri=0.01106136 epo=0 ts=1705540702.707518406,2 min=1705540701.649429217,0 seq=3000} lock=true stat=PENDING rts=1705540701.649429217,0 wto=false gul=1705540702.149429217,0
> --- FAIL: TestQueueLeavesDuplicateBigBatch (4.95s)
> ```
> 
> 🤔

As go test runs concurrently and both of the crdb testservers now use the same version, I doubt if both of testservers are sharing the same data file behind the scene causing the unexpected error.

**Comment by roger2hk** [comment]
The default configuration of testserver stores the data in memory. I suspected that's the root cause failing the tests when two testservers are concurrently reading/writing in the same memory database. Thus, I've added `testserver.StoreOnDiskOpt()` into the latest commit to store the test data in two different on-disk database. The database is saved at `/tmp/cockroach-testserverxxxxxxxx`, with randomly generated `xxxxxxxx` postfix.

**Review by JAORMX — APPROVED** [review]

**Comment by JAORMX** [comment]
@roger2hk that makes sense. Thanks for taking a look!

**Review by AlCutter — APPROVED** [review]

**Pull request merged**
