### PR TITLE
Remove TrillianStatus and TrillianStatusCode

### LINKED ISSUE #335: Use gRPC status to return errors
Consider removing TrillianStatusCode so that clients have a single place to check for errors.

### PR DESCRIPTION
**Pull request by gdbelvin**
Simplify error checking by having a single location to report errors.

Also use standardized error codes for better error processing.

Closes #335

### CODE REVIEW

**Comment by AlCutter** [comment]
I like the idea of switching to standardised error codes, but the `QueueLeaves` call needs to return one status for each queued entry, i.e. a single leaf failing to queue for whatever reason shouldn't abort the whole batch.

**Comment by gdbelvin** [comment]
I agree with you, however, the current api returns only one status for the whole batched `QueueLeaves` request.  Returning one status code per operation requires returning a `map` of some kind between indexes and status codes, bringing us back to #347. 

I suggest we merge this as it maintains the current granularity of error codes, and create a new PR for returning individual error codes once we have a design plan for that.

**Comment by gdbelvin** [comment]
btw, for returning individual error codes, we can use github.com/googleapis/google/rpc/status.proto

**Comment by AlCutter** [comment]
Ok, fair enough - I think we're probably going to get to the API changes in short order, but could you just pop a TODO in there next to the affected APIs if there's not already one?

**Comment by gdbelvin** [comment]
Added TODOs

**Pull request merged**
