### PR TITLE
Re-generate mocks, protos and stringers

### PR DESCRIPTION
**Pull request by RJPercival**

### CODE REVIEW

**Comment by daviddrysdale** [comment]
https://github.com/golang/mock/pull/82 just got merged.

**Comment by RJPercival** [comment]
As @daviddrysdale points out, the Go mock library has recently been adopted by a new maintainer, which means its PRs are finally being reviewed and merged. We should anticipate having to do this more frequently in the near future. Also, there is a new convention for indicating machine-generated files (golang/go#13560), which has resulted in all of our generated code changing.

**Comment by RJPercival** [comment]
To generate the latest versions of these files, I had to do:
`go get -u -t github.com/google/trillian/... github.com/golang/mock/...`

**Comment by daviddrysdale** [comment]
Also cf. https://github.com/google/certificate-transparency-go/pull/29 (hint hint)

**Comment by codingllama** [comment]
Thanks for the replies David and Rob!

**Pull request merged**
