### PR TITLE
Move list/slack to top, add slack invitation

### PR DESCRIPTION
**Pull request by benlaurie**

### CODE REVIEW

**Comment by Martin2112** [comment]
Just wondering why these branches are being created in the main repo and not a fork?

**Comment by benlaurie** [comment]
Could be done in a fork if its a problem.

**Comment by Martin2112** [comment]
Don't think it's a real problem, was just curious. I thought you could
preview via the "View" button in the PR.

Martin

**Comment by benlaurie** [comment]
On 21 February 2018 at 10:52, Martin <notifications@github.com> wrote:

> Don't think it's a real problem, was just curious. I thought you could
> preview via the "View" button in the PR.
>

Possibly so, but then you have to commit and push, if you edit on github
you can preview before committing.


>
> Martin
>

**Pull request merged**
