### PR TITLE
Bump contrib.go.opencensus.io/exporter/stackdriver to v0.13.14

### PR DESCRIPTION
**Pull request by samuelattwood**
Updates contrib.go.opencensus.io/exporter/stackdriver to resolve usage of retracted prometheus module [v2.5.0+incompatible](https://pkg.go.dev/github.com/prometheus/prometheus@v2.5.0+incompatible). Same issue as #2779 - etcd alpha version no longer required.

### Checklist

- [x] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by mhutchinson** [comment]
@samuelattwood do you mind rebasing this to address the conflicts, or would you like one of us to do that?

**Comment by samuelattwood** [comment]
@mhutchinson Rebased 🙂

**Review by mhutchinson — APPROVED** [review]

**Pull request merged**
