### PR TITLE
Add --mysql_max_conns flag to Trillian binaries

### PR DESCRIPTION
**Pull request by RJPercival**
Controls the maximum number of connections each binary can make to the MySQL database. Defaults to approximately one third of the default limit imposed by MySQL. This could be increased if using a MySQL cluster, or if the max_connections setting on the MySQL server has been increased.

This avoids a "[too many connections](https://dev.mysql.com/doc/refman/en/too-many-connections.html)" error under heavy load.

### CODE REVIEW

**Comment by Martin2112** [comment]
It's hard to pick a number of this as it's going to vary based on config and load. Maybe we can document some suggested settings later.

BTW not sure about the logserver setting as it's likely that multiple copies will be run.

**Comment by gdbelvin** [comment]
Hmm, I wonder if a broader discussion about how to have high QPS served from a front end would be helpful? Does each RPC produce it's own connection to the database?

**Comment by RJPercival** [comment]
Each transaction can produce its own connection to the database, so each RPC can produce one or more database connections, depending on how many transactions are required. The Go sql package creates a new connection if it doesn't have an idle one to reuse and, by default, there is no limit to how many connections it will open.

From a quick look at Travis, this change appears to be tanking performance. The integration test looks like it's timing out.

**Comment by Martin2112** [comment]
We might be better off managing this with rate limiting rather than limiting connections.

**Comment by codingllama** [comment]
@Martin2112 I don't think rate limiting removes the need for connection limits. For one, the limits may be high enough that we'd run into this issue even with rate limiting on.

**Comment by Martin2112** [comment]
Typically you'd load test it to find the limits. At some point it won't scale up any more, which might be before it runs out of connections.

**Comment by RJPercival** [comment]
I'm not convinced that reducing the maximum number of SQL connections to 50 was actually having a performance impact. Instead, I think it may have been stalling the integration test for some reason. If I increase that limit to 75 connections, it runs just as fast as with an unlimited number (in ~10 seconds). If we want to go ahead with this PR, I'd best do some more investigating to figure out what's going on.

**Comment by gdbelvin** [comment]
Is this still something that we want?

**Comment by Martin2112** [comment]
I don't think we can solve the problem this way.

Martin

**Comment by gdbelvin** [comment]
Maybe we can close this PR then

**Pull request closed without merging**
