### PR TITLE
storage/mysql: test for parallel duplicate leaves

### PR DESCRIPTION
**Pull request by daviddrysdale**

### CODE REVIEW

**Comment by daviddrysdale** [comment]
For discussion: this test reproduces an oddity I spotted with the hammer changes over at #283.  On adding some tracing, it seems like an INSERT fails with a duplicate primary key, but a subsequent SELECT for the same key (identity hash) fails to find anything, all inside the same transaction.

**Comment by AlCutter** [comment]
+ Martin

**Comment by Martin2112** [comment]
Might be a transaction isolation thing? I'll have a look at it.

**Comment by Martin2112** [comment]
This is probably what we'd expect with the default isolation. The tx that inserts is holding a write lock on the index, which will block the other insert. However the row is not visible to the other transaction until it commits so there's a window where it won't be readable.

**Comment by Martin2112** [comment]
I suppose the next questions are whether this is a problem and if so is there anything we can do about it.

**Comment by dempfi** [comment]
@Martin2112, @daviddrysdale We have spotted a similar issues in our logs. At least it looks like the root cause is the same.

```
W0730 12:16:00.647856 1 tree_storage.go:318] Failed to set merkle subtrees: Error 1062: Duplicate entry '530188640145931381--7' for key 'PRIMARY'
W0730 12:16:00.647882 1 tree_storage.go:392] TX commit flush error: Error 1062: Duplicate entry '530188640145931381--7' for key 'PRIMARY'
```

In order to exactly repro the case I'm trying to add a test case for the `storage/mysql/tree_storage.go` but it appears that it has no direct tests whatsoever.

**Comment by Martin2112** [comment]
It's not possible to consistently update subtrees in parallel for the same map. You probably need something to batch the updates into mutations. Using a Log tree to provide this has the advantage of providing a consistent ordering but it could be done in other ways.

The Map update performance is not where we want it to be yet and there is more work to be done on it.

**Comment by Martin2112** [comment]
It might also be useful to look at the map examples in https://github.com/google/trillian-examples.

**Pull request closed without merging**
