### PR TITLE
Use the extracted merkle library

### PR DESCRIPTION
**Pull request by mhutchinson**
The merkle library in this repo can be marked as deprecated after this. New clients would be better served by using the smaller module, especially for client-side code which will not need all the server-side dependencies that this repository has collected.

### Checklist

- [x] I have updated the [CHANGELOG](CHANGELOG.md).
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by AlCutter** [comment]
Looks like a `goimports` might be needed

**Review by AlCutter — COMMENTED** [review]
You still have references to `github.com/google/trillian/merkle/hashers` in here - the `LogHasher` i/f in that package is now/also in `github.com/transparency-dev/merkle`

**Comment by AlCutter** [comment]
`github.com/google/trillian/merkle/logverifier` structs & funcs are now/also in the `github.com/transparency-dev/merkle` package too

**Comment by AlCutter** [comment]
That last commit seems to have reverted a bunch of references back to the trillian `merkle`, was that intentional?

**Comment by mhutchinson** [comment]
Yep, I figured the various merkle packages here (`merkle`, `internal/merkle` etc) should stay self-contained. If we break that self-containment we should probably do it with aliases to create forward references to the new locations, but that's a big job.

**Comment by AlCutter** [comment]
> Yep, I figured the various merkle packages here (`merkle`, `internal/merkle` etc) should stay self-contained. If we break that self-containment we should probably do it with aliases to create forward references to the new locations, but that's a big job.

Ah, yup, makes sense, ta

**Review by AlCutter — APPROVED** [review]

**Pull request merged**
