### PR TITLE
Bump etcd to 3.2.10 and grpc-gateway to 1.3

### PR DESCRIPTION
**Pull request by gdbelvin**
The current version of grpc-gateway crashes when it encounters a `go_package` with a ";" in it, and this is a feature required to make generated protos comply with internal style guidelines. 
 
These version bumps help us get there by using a recent version of the grpc-gateway. 
I've also bumped the etcd version to keep etcd's dependency on the grpc-gateway in sync.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
The last two commits could do with better messages
 - 'Hack because grpc-gateway #462 wasn't in v1.3' describes *why* you've made the change, it doesn't describe what the change *is*.  
 - Replacing '#462' with a proper URL will prevent the GitHub UI from pointing at the wrong place.
 - 'go generate' would be better as something like 'Regenerate .gw.go files with updated grpc-gateway tools'

**Comment by daviddrysdale** [comment]
More generally, this seems like a lot of effort to 'comply with internal style guidelines' -- maybe we can discuss the background offline?

**Comment by gdbelvin** [comment]
Made the requested commit changes.  I no longer strictly need to use the go_package feature I originally made this PR for, but it may still be a good idea to keep things in the vendor directory roughly up-to-date.

**Comment by daviddrysdale** [comment]
Probably need to wait for a green Travis before trying to merge.

**Pull request merged**
