### PR TITLE
Kill map integration test flake due to nil head

### PR DESCRIPTION
**Pull request by AlCutter**

### CODE REVIEW

**Comment by phad** [comment]
How flaky is this?

**Comment by AlCutter** [comment]
Reasonably flaky, you often get a nil pointer deref here :/

**Comment by phad** [comment]
So the GetSignedMapRoot call returns a non-nil err, but a response r.MapRoot.MapRevision in which r.MapRoot is nil ?

**Comment by AlCutter** [comment]
Or more likely `r` is nil, but yup.

**Comment by phad** [comment]
Feels like a bug more than a race?  (or perhaps both)

**Comment by AlCutter** [comment]
Could be, but given this only happens on Travis I suspect it's perhaps to do with slow IO or something and the crash is not helping with debugging it.

**Pull request closed without merging**
