### PR TITLE
Add map_server to docker-compose.yml

### PR DESCRIPTION
**Pull request by RJPercival**
Makes it easy for people to experiment with the map server.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by RJPercival** [comment]
Worth a CHANGELOG entry?

**Comment by AlCutter** [comment]
Yup, why not :)

**Comment by RJPercival** [comment]
It turns out that the CHANGELOG already covers this since #1479.

**Comment by RJPercival** [comment]
I added a test to make sure the map server is working correctly, which is passing.

**Pull request merged**
