### PR TITLE
Drop use of SQLite

### PR DESCRIPTION
**Pull request by daviddrysdale**
This partly-reverts commit 4023e5ab7de5 ("Use sqlite3 as the default
driver for unit tests (#886)"), removing SQLite as a storage option.

In practice, having a default DB that doesn't support much of the
Trillian functionality (e.g. none of the map tests, none of the
integration tests) has inconvenienced core developers.

However, to allow the core `git clone <repo> ; go test ./...`
scenario to still work without setup dependencies, all DB-using tests
explicitly check for MySQL availability and are skipped if MySQL
is not present.

### CODE REVIEW

**Comment by gdbelvin** [comment]
This might even speed up compile times

**Comment by Martin2112** [comment]
It should speed things up in general by not having to rerun the flaky
builds.

**Comment by daviddrysdale** [comment]
I've added an extra commit with a single reminder test failure -- wdyt?

**Comment by Martin2112** [comment]
This could be worth having. Might need something similar for CloudSpanner tests when they exist. Mentioning no names etc ....

**Pull request merged**
