### PR TITLE
Make the leaf counter metric more usable

### PR DESCRIPTION
**Pull request by pavelkalinnikov**
- Extend the existing leaf counter metric to include pre-ordered logs.
- Add log ID label to distinguish different logs.
- Rename the metric path to not conflict with the existing one.

### CODE REVIEW

**Comment by Martin2112** [comment]
What's the conflicting metric? Renaming and changing the dimensions of it could break existing monitoring. Might be more compatible to add a new metric and deprecate the old one.

**Comment by pavelkalinnikov** [comment]
This PR effectively adds a new metric, it doesn't change the dimensions of the old one (which indeed could be dangerous, because monitoring system might be confused by mismatching schemas).

But it does remove the old metric. I could leave it there and continue to populate it to be 100% safe, but it feels like a pretty useless metric, and on our end we don't use it for alerting etc. I think that removing a metric is equivalent to deprecating it: the jobs just stop reporting it.

**Comment by Martin2112** [comment]
We don't know what monitoring third parties have but maybe it's unlikely to include the old metric. 

Can you update the changelog so if it does break people will know what needs updating.

**Comment by pavelkalinnikov** [comment]
Done.

**Pull request merged**
