### PR TITLE
Add go-licenses to tools.go

### PR DESCRIPTION
**Pull request by RJPercival**
This tool is used when building Docker images, in order to check dependencies have compatible licenses and to comply with those licenses. Including it in tools.go will optimise Docker image builds by fetching the tool when downloading Trillian's dependencies, which are then cached.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly (including the [feature implementation matrix](docs/Feature_Implementation_Matrix.md)).

### CODE REVIEW

**Comment by RJPercival** [comment]
I can see an argument for making the Docker files explicitly grab this tool during the cacheable phase, rather than making it a declared dependency of Trillian. Thoughts?

**Comment by NatalieDoduc** [comment]
(nit: would you mind re-wording your PR description s/This too/go-licences/? Given you also modify tools.go, it's slightly confusing which you're referring to at a quick read.)

What would your alternate proposal look like? `go-licences` is not a dependency, so to speak, more of a helper tool to validate correctness, so your proposal makes more sense to me. That being said, adding it to tools.go is a nice and simple solution.

**Comment by gdbelvin** [comment]
I slightly prefer explicitly referencing this by version during the docker builds
The reason for not automatically putting everything in `tools.go` is that it bloats the dependency list, adding overhead to every `go {build,test,list,install}` operation.

**Comment by gdbelvin** [comment]
bump?

**Comment by RJPercival** [comment]
I'll add an explicit reference in the Dockerfiles instead.

**Pull request closed without merging**
