### PR TITLE
Switch from glog to klog

### PR DESCRIPTION
**Pull request by jdolitsky**
Please see the following explanation of the reasons for klog vs. glog: https://github.com/kubernetes/klog#why-was-klog-created

### CODE REVIEW

**Comment by jdolitsky** [comment]
This should pull in latest go-licenses once this is merged: https://github.com/google/go-licenses/pull/138

**Comment by mhutchinson** [comment]
/gcbrun

I've just rebased this to fix conflicts in the go.mod file

**Comment by mhutchinson** [comment]
I've got #2791 to update to the latest linter, but it doesn't fix this problem. https://github.com/dominikh/go-tools/blob/v0.3.3/go/ir/exits.go#L100 - looks like more work is required upstream in the staticcheck library to detect the `v2` version of `klog`.

**Comment by AlCutter** [comment]
I've rebased/jimmied onto `HEAD` and fixed a few follow-up bits, @hickford would you mind casting an eye over the tweaks so I'm not approving my own code?

**Review by AlCutter — APPROVED** [review]

**Comment by AlCutter** [comment]
Added #2801 to track removing the `//nolint` comments once @mhutchinson's fix to `golangci-lint` is present in a released version.

**Pull request merged**
