### PR TITLE
 crypto: support Ed25519 keypairs

### PR DESCRIPTION
**Pull request by daviddrysdale**
This requires a tweak to the Trillian Signer interface, because the
Ed25519 signing method needs to see the original message rather than
just a hash of it.  For now, special case Ed25519 in a few places and
use a crypto.Hash(0) value to indicate that no hashing is required.

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by Martin2112** [comment]
What about adding an alternative method to our Signer interface, which the other implementations could just return an error from? Just a thought, may not work out.

**Comment by Martin2112** [comment]
Actually that's probably a bad idea if the API isn't a superset of the other. Never mind.

**Comment by daviddrysdale** [comment]
Actually, hold off on reviewing -- I've since found RFC 8410 and I think this can be improved & made more standard.

**Comment by daviddrysdale** [comment]
Now relies on https://github.com/google/certificate-transparency-go/pull/512 and so relies on use of our forked `x509` library for reading/writing key files.

**Comment by gdbelvin** [comment]
It would be most helpful to add context around the decision to not use [x/crypto/ed25519](https://godoc.org/golang.org/x/crypto/ed25519) which is based on RFC 8032.

**Comment by daviddrysdale** [comment]
This does use x/crypto/ed25519 -- see the 6 added imports of that library in the diff.

**Comment by daviddrysdale** [comment]
Because this includes a change to a `.proto` file, now need a CODEOWNER approval.

(Possibly 599173208cadceb84b02c6e0b4295d17653c595d was premature...)

**Pull request merged**
