### PR TITLE
Remove Cloud Spanner support.

### PR DESCRIPTION
**Pull request by pphaneuf**
Part of #2245.

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
I remember from @AlCutter that we run some internal CloudSpanner instance. Defer the review to Al.

**Comment by pphaneuf** [comment]
Sure thing. I *think* we've stopped using that instance, but should get confirmed, @AlCutter should know.

**Comment by AlCutter** [comment]
The CI/CD instance uses CloudSpanner

**Comment by pphaneuf** [comment]
Seems that we're using it for some post-submit testing, so we'll keep it.

**Pull request closed without merging**
