### PR TITLE
Remove toy map client

### PR DESCRIPTION
**Pull request by gdbelvin**
A real map client is located in `client/map_client.go`

### Checklist

- [ ] I have updated the [CHANGELOG](CHANGELOG.md).
  - Adjust the draft version number according to [semantic versioning](https://semver.org/) rules.
- [ ] I have updated [documentation](docs/) accordingly.

### CODE REVIEW

**Comment by AlCutter** [comment]
isn't `client/map_client.go` a library, whereas this is a binary?

**Comment by gdbelvin** [comment]
That is true, but do we want people to use this?
For making rpc calls there is the grpc_cli command line client which may be
more canonical.

**Comment by AlCutter** [comment]
Having a simple toy to play with the map is helpful, I think - perhaps a better idea would be to re-implement this binary using `client/`?

**Comment by Martin2112** [comment]
There is also an example of map usage at: https://github.com/google/trillian-examples/blob/master/etherslurp/mapper/mapper.go

I think removing this early example will be helpful.

**Pull request merged**
