### PR TITLE
updated indentation

### PR DESCRIPTION
**Pull request by vschs007**
indentation adjustments

### CODE REVIEW

**Comment by daviddrysdale** [comment]
The existing ) indentation is the standard layout produced by [gofmt](https://golang.org/cmd/gofmt/), so we'd prefer to leave as-is.

Also, the extra blank line gives too big a gap between the comment and the code it describes, and so the [golint](https://github.com/golang/lint) check in our Travis build complains.

**Comment by vschs007** [comment]
but any issues with this ? any adverse effects ?

**Comment by codingllama** [comment]
Hi Vivek,

In addition to the reasons David mentioned, there's also the fact that we don't encourage whitespace-only changes, as they change the authorship of lines in non-meaningful ways. For example, if I'm tracking a bug I may want to reach out to the previous author for opinion, but if we take whitespace-only changes the authorship goes to the wrong person.

**Comment by vschs007** [comment]
Ok Alan I got it :)

**Comment by vschs007** [comment]
Hi,

Internshala, India's leading online training platform, is offering Online
Winter Trainings in 15+ industry-relevant skills. Learn skills from experts
that will help you in your job/internship search and in your college
project.

The training programs are of 4 to 6 week duration with multiple assignments,
industry-relevant projects, doubt clearing sessions, and can be completed
from the comfort of your home.

Use coupon code ISP8475VIV to avail 55% + 10% discount on all training
programs till 15th October.

To know more about training programs click on the link below.

View Training Programs

Please write to us on this email id (trainings@internshala.com) or give us a
call on +91 8586 080747 (Monday to Saturday, 10:00 AM to 9:00 PM) for any
queries you may have regarding the training program.

Thanks,
Internshala Student Partner (VSCHS007@GMAIL.COM)

**Pull request closed without merging**
