### PR TITLE
Enable code coverage using codecov.io

### PR DESCRIPTION
**Pull request by Martin2112**
Results should be available at:

https://codecov.io/gh/google/trillian

### CODE REVIEW

**Comment by Martin2112** [comment]
I thought it was meant to integrate with Travis via commit status? The setup says you just need to do this config but not where the results surface.

**Comment by daviddrysdale** [comment]
https://codecov.io/gh/google/keytransparency seems to have graphs etc.

**Comment by Martin2112** [comment]
Added link to description. I'll merge it and see if there are other switches that need to be flipped.

I don't think it will affect test run time as we had -cover in the flags before.

**Comment by daviddrysdale** [comment]
BTW (for next time), I was after a link in the commit itself, not in the Github PR description.

(Code hosting services rise and fall, but the Git commit history endures...)

**Pull request merged**
